### ISSUE TITLE
API surface has changed

### ISSUE THREAD

**Issue by fstueber** [NoahNxT/laravel-open-holidays-api#6]
### What happened?

Hi, the OpenHoldiays API surface has changed:

- `HolidayType` got 3 additional values: `National`, `Regional` and `Local`
- New optional enumeration `HolidayQuality` introduced with 2 values: `Mandatory` and `Optional`.

Just to let you know

### How to reproduce the bug

Have a look at the current OpenAPI spec: https://openholidaysapi.org/swagger/v1/swagger.json

### Package Version

0.0.4

### PHP Version

doesn't matter

### Laravel Version

doesn't matter

**Comment by NoahNxT** [comment]
Changes from the will have no impact, checked + tested.

Closing this issues :)

**Comment by NoahNxT** [comment]
Changes from the will have no impact, checked + tested.

Closing this issues 😄
